config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "authors#index"
  resources :authors do
    resources :books
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books 
  accepts_nested_attributes_for :books, allow_destroy: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])

  end
  def new
    @author = Author.new
    @author.books.build
  end

  def create
    @author = Author.create(author_params)
    # debugger
    if @author.save
      redirect_to  @author , notice: "Create Successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
    redirect_to @author, notice: "Update successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end

    def destroy
      @author = Author.find(params[:id])
      @author.destroy
      redirect_to root_path
    end

    private
    def author_params
      params.require(:author).permit(:name, books_attributes:[:id,:title,:_destroy])
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/edit.html.erb
<%= form_with model:@author do | form|%>
<p>Author name:-</P>
<%= form.label :name%>
<%= form.text_field :name%>
<p>Author book details :- </p>
<%= form.fields_for :books do | book_form |%>
<%= book_form.label :title %>
<%= book_form.text_field :title %>
<% end %><br><br>
<%= form.submit %>
<%= link_to 'Back', root_path %>
<% end%>

app/views/authors/index.html.erb
<h1> Authors listing </h2>
<ul>
<% @authors.each do | author |%>
<li><%= link_to author.name, author %></li>
<% end%>
</ul>
<%= link_to 'New author', new_author_path %>

app/views/authors/new.html.erb
<%= form_with model:@author do | form|%>
<p>Author name:-</P>
<%= form.label :name%>
<%= form.text_field :name%>
<p>Author book details :- </p>
<%= form.fields_for :books do | book_form |%>
<%#= book_form.check_box :_d estroy%>
<%= book_form.label :title %>
<%= book_form.text_field :title %>
<% end %><br><br>
<%= form.submit %>
<%= link_to 'Back', root_path %>
<% end%>

app/views/authors/show.html.erb
<html>
  <head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
<body>
  <% flash.each do | message |%>
  <p class="alert alert-info"><%= message %></p>
  <% end %>

  <h3> Authors details page</h3>
  <%= @author.name%>
  <br>
  <%= link_to 'All books',author_books_path(@author) %>
  <%= link_to 'Edit', edit_author_path(@author) %>
  <%= link_to 'Destroy', author_path(@author), data:{
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  }%> 
  <%= link_to 'Back', root_path %>
</body>
</html>

app/views/books/index.html.erb
<%= flash.each do | message |%>
<p style="color:red"><%= message %></p>
<% end%>
<% @books.each do | book|%>
<% if @author == book.author_id%>
<%= book.title%>
<% else %>
<h3>No data</h3>
<% end%>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedForm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>